from django.contrib import admin
from kiterope.models import Profile, User, Goal, Student, Coach, Rate, Session, Review, Update, Post, Plan, Step, Question, Answer, Interest
admin.site.register(Profile)
admin.site.register(Goal)
admin.site.register(Student)
admin.site.register(Coach)
admin.site.register(Rate)
admin.site.register(Session)
admin.site.register(Review)
admin.site.register(Update)
admin.site.register(Post)
admin.site.register(Plan)
admin.site.register(Step)
admin.site.register(Question)
admin.site.register(Answer)
admin.site.register(Interest)
