# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0002_auto_20160903_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='description',
            field=models.CharField(default=' ', max_length=1000),
        ),
    ]
