# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0005_auto_20160906_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='image',
            field=models.FileField(null=True, upload_to='images'),
        ),
    ]
