# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0006_auto_20160906_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='deadline',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
