# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0009_auto_20160907_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='isPublic',
        ),
        migrations.AddField(
            model_name='plan',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kiterope.Goal'),
        ),
        migrations.AddField(
            model_name='plan',
            name='viewableBy',
            field=models.CharField(choices=[('ONLY_ME', 'Only me'), ('SHARED', "Just people I've shared this goal with"), ('MY_COACHES', 'Just my coaches'), ('ALL_COACHES', 'All coaches'), ('ANYONE', 'Anyone')], default='ONLY_ME', max_length=20),
        ),
    ]
