# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0011_auto_20160909_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='plans',
            field=models.ManyToManyField(related_name='plans', to='kiterope.Plan'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='coaches',
            field=models.ManyToManyField(related_name='coaches', to='kiterope.Coach'),
        ),
    ]
