# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0012_auto_20160909_2038'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Step',
        ),
        migrations.RenameField(
            model_name='step',
            old_name='subtasks',
            new_name='substeps',
        ),
        migrations.RenameField(
            model_name='update',
            old_name='task',
            new_name='step',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='tasks',
        ),
        migrations.AddField(
            model_name='plan',
            name='steps',
            field=models.ManyToManyField(related_name='steps', to='kiterope.Step'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='coaches',
            field=models.ManyToManyField(blank=True, related_name='coaches', to='kiterope.Coach'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='plans',
            field=models.ManyToManyField(blank=True, related_name='plans', to='kiterope.Plan'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='updates',
            field=models.ManyToManyField(blank=True, related_name='updates', to='kiterope.Update'),
        ),
    ]
