# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0013_auto_20160911_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='answers',
            field=models.ManyToManyField(blank=True, to='kiterope.Question'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='planTemplates',
            field=models.ManyToManyField(blank=True, to='kiterope.Plan'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='rates',
            field=models.ManyToManyField(blank=True, to='kiterope.Rate'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='kiterope.Review'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='sessions',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='kiterope.Session'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='students',
            field=models.ManyToManyField(blank=True, to='kiterope.Student'),
        ),
        migrations.RemoveField(
            model_name='plan',
            name='goal',
        ),
        migrations.AddField(
            model_name='plan',
            name='goal',
            field=models.ManyToManyField(blank=True, to='kiterope.Goal'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='steps',
            field=models.ManyToManyField(blank=True, related_name='steps', to='kiterope.Step'),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, to='kiterope.Post'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='images',
            field=models.ManyToManyField(blank=True, to='kiterope.Image'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(blank=True, related_name='answers', to='kiterope.Answer'),
        ),
        migrations.AlterField(
            model_name='session',
            name='students',
            field=models.ManyToManyField(blank=True, to='kiterope.Student'),
        ),
        migrations.AlterField(
            model_name='step',
            name='substeps',
            field=models.ManyToManyField(blank=True, to='kiterope.Step'),
        ),
        migrations.AlterField(
            model_name='student',
            name='coaches',
            field=models.ManyToManyField(blank=True, to='kiterope.Coach'),
        ),
        migrations.AlterField(
            model_name='student',
            name='goals',
            field=models.ManyToManyField(blank=True, to='kiterope.Goal'),
        ),
        migrations.AlterField(
            model_name='student',
            name='plans',
            field=models.ManyToManyField(blank=True, to='kiterope.Plan'),
        ),
        migrations.AlterField(
            model_name='student',
            name='questions',
            field=models.ManyToManyField(blank=True, to='kiterope.Question'),
        ),
        migrations.AlterField(
            model_name='student',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='kiterope.Review'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sessions',
            field=models.ManyToManyField(blank=True, to='kiterope.Session'),
        ),
    ]
