# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0014_auto_20160911_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='goal',
            new_name='goals',
        ),
    ]
