# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0016_update_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='calendar',
            field=models.FileField(null=True, upload_to='calendars'),
        ),
    ]
