# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0017_plan_calendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=30)),
                ('email', models.EmailField(max_length=70)),
                ('goal', models.CharField(default=' ', max_length=1000)),
            ],
        ),
    ]
