# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-14 01:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0018_interest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='onSunday',
            new_name='day01',
        ),
        migrations.RenameField(
            model_name='step',
            old_name='onMonday',
            new_name='day02',
        ),
        migrations.RenameField(
            model_name='step',
            old_name='onTuesday',
            new_name='day03',
        ),
        migrations.RenameField(
            model_name='step',
            old_name='onWednesday',
            new_name='day04',
        ),
        migrations.RenameField(
            model_name='step',
            old_name='onThursday',
            new_name='day05',
        ),
        migrations.RenameField(
            model_name='step',
            old_name='onFriday',
            new_name='day06',
        ),
        migrations.RenameField(
            model_name='step',
            old_name='onSaturday',
            new_name='day07',
        ),
        migrations.RenameField(
            model_name='update',
            old_name='measurement',
            new_name='floatMeasurement',
        ),
        migrations.RemoveField(
            model_name='update',
            name='goal',
        ),
        migrations.AddField(
            model_name='plan',
            name='scheduleLength',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='plan',
            name='templatePlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kiterope.Plan'),
        ),
        migrations.AddField(
            model_name='plan',
            name='timeMetric',
            field=models.CharField(choices=[('DAY', 'Day'), ('WEEK', 'Week'), ('MONTH', 'Month')], default='WEEK', max_length=10),
        ),
        migrations.AddField(
            model_name='step',
            name='begins',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='step',
            name='date',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='ends',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='step',
            name='title',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='update',
            name='audioMeasurement',
            field=models.FileField(null=True, upload_to='updates_audio'),
        ),
        migrations.AddField(
            model_name='update',
            name='integerMeasurement',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='metric',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='update',
            name='videoMeasurement',
            field=models.FileField(null=True, upload_to='updates_video'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='endDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='startDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='description',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.RemoveField(
            model_name='step',
            name='duration'
        ),
        migrations.AddField(
            model_name='step',
            name='duration',
            field=models.IntegerField(null=True),
        ),

    ]
