# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-14 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0019_auto_20161014_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='frequency',
            field=models.CharField(choices=[('ONCE', 'Once'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='ONCE', max_length=20),
        ),
    ]
