# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-24 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0020_auto_20161014_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='deadline',
            field=models.CharField(default=' ', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='description',
            field=models.CharField(default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='why',
            field=models.CharField(default=' ', max_length=200, null=True),
        ),
    ]
