# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-01 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0021_auto_20161024_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='deadline',
            field=models.CharField(blank=True, default=' ', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='description',
            field=models.CharField(blank=True, default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='title',
            field=models.CharField(blank=True, default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='goal',
            name='votes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='why',
            field=models.CharField(blank=True, default=' ', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='calendar',
            field=models.FileField(blank=True, null=True, upload_to='calendars'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='endDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='startDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kiterope.Plan'),
        ),
    ]
