# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-01 23:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0023_auto_20161101_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='plan',
            new_name='plans',
        ),
    ]
