# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-01 23:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0024_auto_20161101_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='plans',
        ),
        migrations.AddField(
            model_name='step',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kiterope.Plan'),
        ),
    ]
