# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-02 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0025_auto_20161101_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='substeps',
        ),
    ]
