# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-02 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0029_auto_20161102_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
