# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0030_auto_20161102_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='endTime',
            field=models.CharField(blank=True, default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='step',
            name='startTime',
            field=models.CharField(blank=True, default=' ', max_length=20),
        ),
    ]
