# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 00:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0031_auto_20161109_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='endTime',
        ),
    ]
