# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-16 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0033_auto_20161115_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='endDate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='startDate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planoccurrence',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stepoccurrence',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
