# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-18 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0035_auto_20161117_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepoccurrence',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
