# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-18 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0036_auto_20161118_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepoccurrence',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
