# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-22 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0037_auto_20161118_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepoccurrence',
            name='posts',
            field=models.ManyToManyField(blank=True, to='kiterope.Post'),
        ),
        migrations.AddField(
            model_name='stepoccurrence',
            name='updates',
            field=models.ManyToManyField(blank=True, to='kiterope.Update'),
        ),
    ]
