# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-24 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0038_auto_20161122_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='step',
        ),
        migrations.AddField(
            model_name='update',
            name='stepOccurrence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kiterope.StepOccurrence'),
        ),
    ]
