# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-29 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0040_auto_20161129_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='author',
        ),
        migrations.AddField(
            model_name='step',
            name='update01',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update01', to='kiterope.Update'),
        ),
        migrations.AddField(
            model_name='step',
            name='update02',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update02', to='kiterope.Update'),
        ),
        migrations.AddField(
            model_name='step',
            name='update03',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update03', to='kiterope.Update'),
        ),
    ]
