# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-03 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0042_auto_20161130_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='metric',
        ),
        migrations.AddField(
            model_name='update',
            name='format',
            field=models.CharField(choices=[('text', 'text'), ('integer', 'integer'), ('float', 'float'), ('url', 'url'), ('picture', 'picture'), ('video', 'video'), ('audio', 'audio')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='update',
            name='measuringWhat',
            field=models.CharField(default='emotions and thoughts', max_length=30),
        ),
        migrations.AddField(
            model_name='update',
            name='units',
            field=models.CharField(blank=True, default=' ', max_length=10, null=True),
        ),
    ]
