# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-07 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0043_auto_20161203_0141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updateoccurrence',
            old_name='float',
            new_name='decimal',
        ),
        migrations.AddField(
            model_name='updateoccurrence',
            name='longText',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='updateoccurrence',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='updateoccurrence',
            name='text',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
