# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-07 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0044_auto_20161207_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stepoccurrence',
            name='updates',
        ),
        migrations.AlterField(
            model_name='updateoccurrence',
            name='stepOccurrence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stepOccurrence', to='kiterope.StepOccurrence'),
        ),
        migrations.AlterField(
            model_name='updateoccurrence',
            name='update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update', to='kiterope.Update'),
        ),
        migrations.AlterField(
            model_name='updateoccurrence',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
