# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-07 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0046_auto_20161207_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateoccurrence',
            name='stepOccurrence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stepOccurrence', to='kiterope.StepOccurrence'),
        ),
        migrations.AlterField(
            model_name='updateoccurrence',
            name='update',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update', to='kiterope.Update'),
        ),
    ]
