# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-08 02:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0049_auto_20161207_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='date',
            new_name='monthlyDates',
        ),
    ]
