# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-08 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0050_auto_20161208_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='monthlyDates',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
