# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-08 02:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0051_auto_20161208_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='begins',
        ),
        migrations.RemoveField(
            model_name='step',
            name='ends',
        ),
        migrations.RemoveField(
            model_name='step',
            name='wasCompleted',
        ),
    ]
