# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-08 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0052_auto_20161208_0210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='timeMetric',
        ),
        migrations.AlterField(
            model_name='plan',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
