# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 20:59
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0053_auto_20161208_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
