# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-16 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0055_auto_20161216_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='images',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='isStudent',
        ),
        migrations.AddField(
            model_name='profile',
            name='firstName',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastName',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profilePhoto',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='profile',
            name='zipCode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
