# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-21 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0056_auto_20161216_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='absoluteEndDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='absoluteStartDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(blank=True, default='America/Los_Angeles', null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='useAbsoluteTime',
            field=models.BooleanField(default=False),
        ),
    ]
