# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-16 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0057_auto_20161221_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='plan',
            name='costFrequencyMetric',
            field=models.CharField(choices=[('FREE', 'FREE'), ('MONTH', 'Per Month'), ('ONE_TIME', 'One Time')], default='PER MONTH', max_length=20),
        ),
        migrations.AddField(
            model_name='plan',
            name='timeCommitment',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='step',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
