# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-16 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0058_auto_20170116_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
