# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-16 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0059_plan_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='endDate',
        ),
        migrations.AlterField(
            model_name='plan',
            name='scheduleLength',
            field=models.CharField(choices=[('1w', '1 week'), ('2w', '2 weeks'), ('3w', '3 weeks'), ('1m', '1 month'), ('6w', '6 weeks'), ('2m', '2 months'), ('10w', '10 weeks'), ('3m', '3 months'), ('4m', '4 months'), ('5m', '5 months'), ('6m', '6 months'), ('7m', '7 months'), ('8m', '8 months'), ('9m', '9 months'), ('10m', '10 months'), ('11m', '11 months'), ('1y', '1 year')], default='3m', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='viewableBy',
            field=models.CharField(choices=[('ONLY_ME', 'Only me'), ('ONLY_CLIENTS', 'Just my clients'), ('ANYONE', 'Anyone')], default='ONLY_ME', max_length=20),
        ),
    ]
