# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-21 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0060_auto_20170116_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='costFrequencyMetric',
            field=models.CharField(choices=[('FREE', 'Free'), ('MONTH', 'Per Month'), ('ONE_TIME', 'One Time')], default='PER MONTH', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='timeCommitment',
            field=models.CharField(blank=True, choices=[('1h', '1 hour per day'), ('2h', '2 hour per day'), ('3h', '3 hours per day'), ('4h', '4 hours per day'), ('5h', '5 hours per day'), ('8h', '8 hours per day')], default='1h', max_length=100),
        ),
    ]
