# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-21 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0061_auto_20170121_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
