# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-27 01:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0064_auto_20170127_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='hasMetric',
        ),
    ]
