# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-27 01:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0065_remove_goal_hasmetric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='priority',
        ),
    ]
