# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-30 19:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kiterope', '0066_remove_goal_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('INITIATING USER', 'Initiating User'), ('USER', 'User'), ('INITIATING COACH', 'Initiating Coach'), ('COACH', 'Coach')], max_length=20)),
                ('joiningTime', models.DateTimeField(null=True)),
                ('leavingTime', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='session',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='session',
            name='isGroup',
        ),
        migrations.RemoveField(
            model_name='session',
            name='media',
        ),
        migrations.RemoveField(
            model_name='session',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='session',
            name='students',
        ),
        migrations.AddField(
            model_name='session',
            name='rate',
            field=models.ManyToManyField(blank=True, to='kiterope.Rate'),
        ),
        migrations.AddField(
            model_name='session',
            name='tokBoxSessionId',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='session',
            name='tokBoxToken',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='session',
            name='type',
            field=models.CharField(choices=[('TRIAL', 'Trial'), ('PAID', 'Paid')], default='TRIAL', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='participants',
            field=models.ManyToManyField(blank=True, to='kiterope.Participant'),
        ),
    ]
