# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-31 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0068_auto_20170131_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='session',
            name='rate',
        ),
        migrations.AddField(
            model_name='session',
            name='rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kiterope.Rate'),
        ),
    ]
