# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-07 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0070_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
