# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-07 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0072_label_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='labels', to='kiterope.Label'),
        ),
    ]
