# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0083_auto_20170405_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='title',
            field=models.CharField(default=' ', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='why',
            field=models.CharField(default=' ', max_length=2000),
        ),
    ]
