# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 19:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0085_auto_20170411_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='updates',
        ),
        migrations.AlterField(
            model_name='goal',
            name='deadline',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='why',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
