# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0087_auto_20170411_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='title',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
