# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 23:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kiterope', '0091_room_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='krmessage',
            name='handle',
        ),
        migrations.AddField(
            model_name='krmessage',
            name='channel',
            field=models.TextField(default='notifications'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='krmessage',
            name='sender',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='krmessage',
            name='typeOfMessage',
            field=models.TextField(choices=[('CALL', 'Call'), ('TEXT', 'Text'), ('NOTIFICATION_REFERENCE', 'Notification Reference')], default='NOTIFICATION'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='permission',
            field=models.TextField(default='ReceiverOrSenderOnly'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('CALL', 'Call'), ('TEXT', 'Text'), ('NOTIFICATION_REFERENCE', 'Notification Reference')], max_length=20),
        ),
    ]
