# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 00:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0092_auto_20170413_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='krmessage',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='krmessage',
            name='typeOfMessage',
            field=models.TextField(choices=[('CALL', 'Call'), ('TEXT', 'Text'), ('NOTIFICATION_REFERENCE', 'Notification Reference'), ('NOTIFICATION', 'Notification')]),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('CALL', 'Call'), ('TEXT', 'Text'), ('NOTIFICATION_REFERENCE', 'Notification Reference'), ('NOTIFICATION', 'Notification')], max_length=20),
        ),
    ]
