# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0093_auto_20170414_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='notificationRoom',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='kiterope.Room'),
        ),
    ]
