# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0094_auto_20170414_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='label',
            field=models.TextField(max_length=16, unique=True),
        ),
    ]
