# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 16:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kiterope', '0107_auto_20170415_0111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(max_length=16, unique=True)),
                ('permission', models.CharField(choices=[('ONLYRECEIVER_ONLYSENDER', 'Only receiver and sender'), ('ONLYRECEIVER_ANYSENDER', 'Only receiver, any sender')], default='ONLYRECEIVER_ONLYSENDER', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiterope.Channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='users',
        ),
        migrations.RemoveField(
            model_name='roomuser',
            name='room',
        ),
        migrations.RemoveField(
            model_name='roomuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='notificationRoom',
        ),
        migrations.AlterField(
            model_name='krmessage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='krmessages', to='kiterope.Channel'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default=' ', max_length=2000),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='RoomUser',
        ),
        migrations.AddField(
            model_name='channel',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='kiterope_channel_related', through='kiterope.ChannelUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='channel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kiterope.Channel'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notificationChannel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kiterope.Channel'),
        ),
    ]
