# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0108_auto_20170418_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='krmessage',
            name='channel',
        ),
    ]
