# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0109_remove_krmessage_channel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='krmessage',
            old_name='room',
            new_name='channel',
        ),
    ]
