# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0111_auto_20170418_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='message',
            name='typeOfMessage',
            field=models.TextField(choices=[('CALL', 'Call'), ('TEXT', 'Text'), ('NOTIFICATION_REFERENCE', 'Notification Reference'), ('NOTIFICATION', 'Notification')], default='chat-messages'),
            preserve_default=False,
        ),
    ]
