# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0112_auto_20170420_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='plans',
        ),
        migrations.AlterField(
            model_name='goal',
            name='viewableBy',
            field=models.CharField(choices=[('ONLY_ME', 'Only me'), ('SHARED', "Just people I've shared this with"), ('ONLY_COACHES', 'Just my coaches'), ('ALL_COACHES', 'All coaches'), ('ANYONE', 'Anyone')], default='ONLY_ME', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilePhoto',
            field=models.CharField(blank=True, default='images/user.svg', max_length=200, null=True),
        ),
    ]
