# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0114_auto_20170428_0509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='contacts',
        ),
    ]
