# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0116_auto_20170428_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='wasConfirmed',
            field=models.CharField(blank=True, default=' ', max_length=20),
        ),
    ]
