# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0119_remove_profile_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='planoccurrence',
            name='isSubscribed',
            field=models.BooleanField(default=True),
        ),
    ]
