# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0120_planoccurrence_issubscribed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='calendar',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='templatePlan',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='users',
        ),
    ]
