# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0121_auto_20170505_0550'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plan',
            new_name='Program',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='planTemplates',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='rates',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='sessions',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='students',
        ),
        migrations.RemoveField(
            model_name='student',
            name='coaches',
        ),
        migrations.RemoveField(
            model_name='student',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='student',
            name='plans',
        ),
        migrations.RemoveField(
            model_name='student',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='student',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sessions',
        ),
        migrations.RemoveField(
            model_name='student',
            name='settings',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RenameField(
            model_name='planoccurrence',
            old_name='plan',
            new_name='program',
        ),
        migrations.RenameField(
            model_name='step',
            old_name='plan',
            new_name='program',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='coaches',
        ),
        migrations.DeleteModel(
            name='Coach',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
