# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0123_auto_20170517_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
