# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-03 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0124_step_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='format',
            field=models.CharField(choices=[('text', 'text'), ('integer', 'integer'), ('decimal', 'decimal'), ('url', 'url'), ('picture', 'picture'), ('video', 'video'), ('audio', 'audio')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='step',
            name='image',
            field=models.CharField(blank=True, default='images/stepDefaultImage.svg', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='format',
            field=models.CharField(choices=[('text', 'text'), ('integer', 'integer'), ('decimal', 'decimal'), ('url', 'url'), ('picture', 'picture'), ('video', 'video'), ('audio', 'audio')], default='text', max_length=10),
        ),
    ]
