# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0125_auto_20170603_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notificationMethod',
            field=models.CharField(choices=[('EMAIL_AND_TEXT', 'Email and Text'), ('EMAIL', 'Email Only'), ('TEXT', 'Text Only'), ('NO_NOTIFICATIONS', "I don't want any notifications")], default='EMAIL', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='notificationPhone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
    ]
