# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0126_auto_20170616_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notificationEmail',
            field=models.EmailField(blank=True, max_length=70),
        ),
    ]
