# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0128_remove_profile_notificationemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='notificationMethod',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='notificationPhone',
        ),
        migrations.AddField(
            model_name='planoccurrence',
            name='notificationEmail',
            field=models.EmailField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='planoccurrence',
            name='notificationMethod',
            field=models.CharField(choices=[('EMAIL_AND_TEXT', 'Email and Text'), ('EMAIL', 'Email Only'), ('TEXT', 'Text Only'), ('NO_NOTIFICATIONS', "I don't want any notifications")], default='NO_NOTIFICATIONS', max_length=20),
        ),
        migrations.AddField(
            model_name='planoccurrence',
            name='notificationPhone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
    ]
