# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0131_auto_20170708_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='category',
            field=models.CharField(choices=[('UNCATEGORIZED', 'Uncategorized'), ('HEALTH_AND_FITNESS', 'Health & Fitness'), ('FAMILY', 'Family'), ('RELATIONSHIPS', 'Relationships'), ('CAREER', 'Career'), ('EDUCATION_AND_SKILLS', 'Education & Skills'), ('MONEY', 'Money')], default='UNCATEGORIZED', max_length=20),
        ),
    ]
