# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0132_program_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='expoPushToken',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='planoccurrence',
            name='isSubscribed',
            field=models.BooleanField(default=False),
        ),
    ]
