# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0135_auto_20170817_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expopushtoken',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='expoPushToken',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ExpoPushToken',
        ),
    ]
