# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-22 01:05
from __future__ import unicode_literals

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0136_auto_20170818_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(blank=True, default='America/Los_Angeles', null=True),
        ),
    ]
