# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-24 22:03
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0138_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
