# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-16 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0139_auto_20170824_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='viewableBy',
            field=models.CharField(choices=[('ONLY_ME', 'Only me'), ('ANYONE', 'Anyone')], default='ONLY_ME', max_length=20),
        ),
        migrations.AlterField(
            model_name='program',
            name='viewableBy',
            field=models.CharField(choices=[('ONLY_ME', 'Only me'), ('ANYONE', 'Anyone')], default='ONLY_ME', max_length=20),
        ),
        migrations.AlterField(
            model_name='updateoccurrence',
            name='audio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='updateoccurrence',
            name='picture',
        ),
        migrations.AlterField(
            model_name='updateoccurrence',
            name='video',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
