# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-23 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0141_profile_utcmidnight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='utcMidnight',
            field=models.CharField(blank=True, default='00:00', max_length=5, null=True),
        ),
    ]
