# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-27 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0142_auto_20170923_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='obstacles',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
