# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-29 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0145_auto_20170929_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planoccurrence',
            name='notificationMethod',
            field=models.CharField(choices=[('APP_TEXT_EMAIL', 'App, Text, and Email'), ('APP_TEXT', 'App and Text'), ('APP_EMAIL', 'App and Email'), ('TEXT_EMAIL', 'Text and Email'), ('APP', 'App Only'), ('TEXT', 'Text Only'), ('EMAIL', 'Email Only'), ('NO_NOTIFICATIONS', "I don't want any notifications")], default='NO_NOTIFICATIONS', max_length=20),
        ),
        migrations.AlterField(
            model_name='settingsset',
            name='defaultNotificationMethod',
            field=models.CharField(choices=[('APP_TEXT_EMAIL', 'App, Text, and Email'), ('APP_TEXT', 'App and Text'), ('APP_EMAIL', 'App and Email'), ('TEXT_EMAIL', 'Text and Email'), ('APP', 'App Only'), ('TEXT', 'Text Only'), ('EMAIL', 'Email Only'), ('NO_NOTIFICATIONS', "I don't want any notifications")], default='NO_NOTIFICATIONS', max_length=20),
        ),
    ]
