# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-09 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0147_step_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepoccurrence',
            name='type',
            field=models.CharField(choices=[('COMPLETION', 'Completion-Based Step'), ('TIME', 'Time-Based Step')], default='COMPLETION', max_length=30),
        ),
        migrations.AlterField(
            model_name='step',
            name='type',
            field=models.CharField(choices=[('COMPLETION', 'Completion-Based Step'), ('TIME', 'Time-Based Step')], default='COMPLETION', max_length=30),
        ),
    ]
