# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-10 21:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kiterope', '0148_auto_20171009_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visualization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('kind', models.CharField(blank=True, choices=[('LINE', 'Line Graph'), ('BAR', 'Bar Graph')], max_length=15)),
                ('dependentVariable', models.CharField(blank=True, max_length=50)),
                ('independentVariable', models.CharField(blank=True, max_length=50)),
                ('mediatorVariable', models.CharField(blank=True, max_length=50)),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kiterope.Step')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
