# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-12 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0149_visualization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='step',
        ),

        migrations.AddField(
            model_name='update',
            name='steps',
            field=models.ManyToManyField(to='kiterope.Step'),
        ),
    ]
