# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-12 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0150_auto_20171012_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='steps',
            field=models.ManyToManyField(related_name='kiterope_stepupdate', to='kiterope.Step'),
        ),
    ]
