# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-20 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0154_auto_20171019_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualization',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kiterope.Program'),
        ),
    ]
