# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-20 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0155_visualization_program'),
    ]

    operations = [
    ]
