# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-20 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0156_update_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='update',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kiterope.Program'),
        ),
    ]
