# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-23 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0158_auto_20171023_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualization',
            name='dependentVariable',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='independentVariable',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='mediatorVariable',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
