# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-24 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0159_auto_20171023_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
