# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-25 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0163_auto_20171024_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateoccurrence',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
