# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-25 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0164_auto_20171025_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualization',
            name='dependentVariable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visualization_dependendentVariable', to='kiterope.Update'),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='independentVariable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visualization_independendentVariable', to='kiterope.Update'),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='mediatorVariable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visualization_mediatorVariable', to='kiterope.Update'),
        ),
    ]
