# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-03 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0165_auto_20171025_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualization',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kiterope.PlanOccurrence'),
        ),
    ]
