# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-05 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0166_visualization_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepoccurrence',
            name='previouslySaved',
            field=models.BooleanField(default=False),
        ),
    ]
