# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-10 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0167_stepoccurrence_previouslysaved'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='costFrequencyMetric',
            field=models.CharField(choices=[('MONTH', 'Per Month'), ('WEEK', 'Per Week'), ('ONE_TIME', 'One Time')], default='MONTH', max_length=20),
        ),
    ]
