# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-18 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0168_auto_20180110_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='CroppableImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originalUncompressedImage', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('cropperImageData', picklefield.fields.PickledObjectField(editable=False)),
                ('cropperCropboxData', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='step',
            name='croppableImage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kiterope.CroppableImage'),
        ),
    ]
