# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-18 21:35
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0169_auto_20180118_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croppableimage',
            name='cropperCropboxData',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='croppableimage',
            name='cropperImageData',
            field=jsonfield.fields.JSONField(),
        ),
    ]
