# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-18 21:39
from __future__ import unicode_literals

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0170_auto_20180118_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croppableimage',
            name='cropperCropboxData',
            field=picklefield.fields.PickledObjectField(editable=False),
        ),
        migrations.AlterField(
            model_name='croppableimage',
            name='cropperImageData',
            field=picklefield.fields.PickledObjectField(editable=False),
        ),
    ]
