# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-18 22:54
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0171_auto_20180118_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croppableimage',
            name='cropperCropboxData',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='croppableimage',
            name='cropperImageData',
            field=jsonfield.fields.JSONField(),
        ),
    ]
