# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-19 00:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0173_auto_20180118_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='croppableimage',
            name='cropperCropboxData',
        ),
        migrations.RemoveField(
            model_name='croppableimage',
            name='cropperImageData',
        ),
    ]
