# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-19 00:10
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0174_auto_20180119_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='croppableimage',
            name='cropperCropboxData',
            field=jsonfield.fields.JSONField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='croppableimage',
            name='cropperImageData',
            field=jsonfield.fields.JSONField(blank=True, default='', null=True),
        ),
    ]
