# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-26 00:44
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0176_croppableimage_croppercanvasdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='croppableimage',
            name='cropperData',
            field=jsonfield.fields.JSONField(blank=True, default='', null=True),
        ),
    ]
