# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-26 01:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0177_croppableimage_cropperdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='croppableimage',
            name='cropperData',
        ),
    ]
