# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-27 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0179_auto_20180126_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='croppableImage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kiterope.CroppableImage'),
        ),
    ]
