# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-02 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0182_auto_20180201_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='croppableimage',
            name='title',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
