# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-06 20:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kiterope', '0186_auto_20180330_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiterope.Goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='croppableImage',
            field=models.ForeignKey(default='214', null=True, on_delete=django.db.models.deletion.CASCADE, to='kiterope.CroppableImage'),
        ),
    ]
