# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-06 23:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kiterope', '0187_auto_20180406_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='programrequest',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programRequest_receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
