# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-13 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0188_programrequest_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualization',
            name='kind',
            field=models.CharField(blank=True, choices=[('LINE', 'Line Graph'), ('BAR', 'Bar Graph'), ('SPREADSHEET', 'Spreadsheet')], max_length=15),
        ),
    ]
