# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-25 23:28
from __future__ import unicode_literals

from django.db import migrations
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0191_auto_20180425_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='recurrence',
        ),
        migrations.AddField(
            model_name='step',
            name='recurrence',
            field=recurrence.fields.RecurrenceField(blank=True, null=True),
        ),
    ]
