# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-04 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0197_auto_20180504_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='endRecurrence',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='step',
            name='interval',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='step',
            name='monthlyDay',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='step',
            name='monthlyDayOption',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='step',
            name='monthlySpecificity',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='step',
            name='numberOfOccurrences',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
