# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-04 23:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0198_auto_20180504_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='recurrence',
        ),
    ]
