# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-13 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0200_step_recurrencerule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='frequency',
            field=models.CharField(choices=[('ONCE', 'Once'), ('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='ONCE', max_length=20),
        ),
    ]
