# Generated by Django 2.0.6 on 2018-06-22 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0201_auto_20180613_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planoccurrence',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kiterope.Goal'),
        ),
        migrations.AlterField(
            model_name='planoccurrence',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kiterope.Program'),
        ),
        migrations.AlterField(
            model_name='planoccurrence',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='croppableImage',
            field=models.ForeignKey(default='214', null=True, on_delete=django.db.models.deletion.PROTECT, to='kiterope.CroppableImage'),
        ),
        migrations.AlterField(
            model_name='programrequest',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kiterope.Goal'),
        ),
        migrations.AlterField(
            model_name='programrequest',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programRequest_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='programrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='session',
            name='rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kiterope.Rate'),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kiterope.Step'),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
