# Generated by Django 2.0.6 on 2018-06-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0202_auto_20180622_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='stripeProductId',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
