# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-26 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0204_auto_20180626_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
