# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-26 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0205_auto_20180626_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='stripePlanId',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
