# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-26 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0206_program_stripeplanid'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planId', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='program',
            name='stripePlanId',
        ),
        migrations.AddField(
            model_name='planoccurrence',
            name='stripePlanId',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
