# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-26 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0210_profile_stripecustomerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stripeSourceId',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
