# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-26 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0211_profile_stripesourceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='costFrequencyMetric',
            field=models.CharField(choices=[('once', 'One Time'), ('month', 'Per Month'), ('week', 'Per Week'), ('day', 'Per Day'), ('year', 'Per Year')], default='MONTH', max_length=20),
        ),
    ]
