# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-02 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0213_profile_sourceattached'),
    ]

    operations = [
        migrations.AddField(
            model_name='planoccurrence',
            name='stripeSubscriptionId',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='planoccurrence',
            name='notificationMethod',
            field=models.CharField(choices=[('APP_TEXT_EMAIL', 'App, Text, and Email'), ('APP_TEXT', 'App and Text'), ('APP_EMAIL', 'App and Email'), ('TEXT_EMAIL', 'Text and Email'), ('APP', 'App Only'), ('TEXT', 'Text Only'), ('EMAIL', 'Email Only'), ('NO_NOTIFICATIONS', "I don't want any notifications")], default='EMAIL', max_length=20),
        ),
    ]
