# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-05 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0214_auto_20180702_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default=' ', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notificationChannel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kiterope.KChannel'),
        ),
    ]
