# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-05 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0218_remove_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('contacts', models.ManyToManyField(blank=True, related_name='contactGroup_userProfiles', to='kiterope.Profile')),
                ('profile', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='kiterope.Profile')),
            ],
        ),
    ]
