# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-05 22:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0219_contactgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='relationship',
        ),
    ]
