# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-12 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0222_contact_contactgroups'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactgroup',
            name='isDefault',
            field=models.BooleanField(default=False),
        ),
    ]
