# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-17 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0227_auto_20180716_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='metricLabel',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='update',
            name='name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='update',
            name='units',
            field=models.CharField(blank=True, default=' ', max_length=30, null=True),
        ),
    ]
