# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-20 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0229_domain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='logo',
            new_name='desktopLogo',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='primaryColor',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='secondaryColor',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='tertiaryColor',
        ),
        migrations.AddField(
            model_name='domain',
            name='color1bg',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AddField(
            model_name='domain',
            name='color1txt',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AddField(
            model_name='domain',
            name='color2bg',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AddField(
            model_name='domain',
            name='color2txt',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AddField(
            model_name='domain',
            name='color3bg',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AddField(
            model_name='domain',
            name='color3txt',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AddField(
            model_name='domain',
            name='color4bg',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AddField(
            model_name='domain',
            name='color4txt',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AddField(
            model_name='domain',
            name='mobileLogo',
            field=models.CharField(default='', max_length=255),
        ),
    ]
