# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-20 19:53
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0230_auto_20180720_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='color1bg',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AlterField(
            model_name='domain',
            name='color1txt',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
        migrations.AlterField(
            model_name='domain',
            name='color2bg',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AlterField(
            model_name='domain',
            name='color2txt',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
        migrations.AlterField(
            model_name='domain',
            name='color3bg',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AlterField(
            model_name='domain',
            name='color3txt',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
        migrations.AlterField(
            model_name='domain',
            name='color4bg',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AlterField(
            model_name='domain',
            name='color4txt',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
    ]
