# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-26 23:04
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0231_auto_20180720_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='updateoccurrence',
            name='pictures',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), null=True, size=None),
        ),
    ]
