# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-26 23:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0232_updateoccurrence_pictures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updateoccurrence',
            name='pictures',
        ),
    ]
