# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-27 00:16
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0234_auto_20180726_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updateoccurrence',
            name='pictures',
        ),
        migrations.AddField(
            model_name='updateoccurrence',
            name='pictures',
            field=jsonfield.fields.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UrlClass',
        ),
    ]
