# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-31 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiterope', '0235_auto_20180727_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='updateoccurrence',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='format',
            field=models.CharField(choices=[('text', 'text'), ('integer', 'integer'), ('decimal', 'decimal'), ('url', 'url'), ('picture', 'picture'), ('video', 'video'), ('audio', 'audio'), ('boolean', 'boolean'), ('datetime', 'datetime'), ('duration', 'duration')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='update',
            name='format',
            field=models.CharField(choices=[('text', 'text'), ('integer', 'integer'), ('decimal', 'decimal'), ('url', 'url'), ('picture', 'picture'), ('video', 'video'), ('audio', 'audio'), ('boolean', 'boolean'), ('datetime', 'datetime'), ('duration', 'duration')], default='text', max_length=30),
        ),
        migrations.AlterField(
            model_name='update',
            name='measuringWhat',
            field=models.CharField(max_length=50),
        ),
    ]
